### ISSUE TITLE
cabal install fails on GHC 6.12.3

### ISSUE THREAD

**Issue by xiaoruoruo** [serras/scion-class-browser#10]
The message is:

```
src/Scion/Browser.hs:12:17:
    Could not find module `Data.ByteString':
      It is a member of the hidden package `bytestring-0.9.1.7'.
      Perhaps you need to add `bytestring' to the build-depends in your .cabal file.
      Use -v to see a list of the files searched for.
```

**Comment by serras** [comment]
In principle, scion-browser targets the current version of GHC in the Haskell Platform, which is 7.0.3.
However, you can try downloading the package .tar.gz from http://hackage.haskell.org/package/scion-browser-0.1.3.3, unpacking it, and change the lines 59 and 144 to add "bytestring" to the list. Then run "cabal install" in the place where you unpacked the things.
If it works, please report back so we can change it upstream.

**Comment by xiaoruoruo** [comment]
Thanks. I did a "cabal install" and it fails with:

```
Building scion-browser-0.1.3.3...

src/Scion/Browser/Util.hs:12:7:
    Could not find module `GHC.Conc.Sync':
      Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
scion-browser-0.1.3.3 failed during the building phase. The exception was:
ExitFailure 1
```

Seems like cabal didn't find a global package?
Maybe I will just update Haskell Platform

**Comment by serras** [comment]
May you try cloning the current repo (`git clone git://github.com/serras/scion-class-browser.git`) and building against it?
Maybe you will need to remove the test-suite section from your Cabal file, because ghc 6.12 will ship an older version of Cabal and may not support it.

**Comment by xiaoruoruo** [comment]
It is compiling! Thanks for your time

BTW, cabal ignores the test-suite:

```
Warning: scion-browser.cabal: Ignoring unknown section type: test-suite
```
