### ISSUE TITLE
Hello,how to install this one

### ISSUE THREAD

**Issue by AlexLuya** [serras/scion-class-browser#11]
I  have read this:http://eclipsefp.github.com/dev.html,there is information about how to install Buildwrapper but no info about how to install this one.So,how to install and use this one.By the way I am using:ghc7.0.3,eclipse .37,ubuntu 11.10 64bit.

**Comment by serras** [comment]
You can just clone the repository and then make "cabal install" in the folder where you cloned it.
However, if you are using scion-browser just for EclipseFP, the plug-in should install scion-browser for you.

**Comment by AlexLuya** [comment]
## I tried to run:cabal install,but got:

cabal: scion-browser.cabal:121: The 'type' field is required for test suites.

## The available test types are: exitcode-stdio-1.0

My configuration is:ubuntu 11.10 64bit,GHC 7.0.3,eclipse 3.7 64bit,

## when I run:cabal --version,got this:

cabal-install version 0.10.2
using version 1.10.1.0 of the Cabal library

**Comment by serras** [comment]
That's strange, because you can check that the scion-browser.cabal file has a type field for its testsuite. Indeed, it's working in my machine. You can try deleting lines from 121 to the end the current Cabal file doesn't work for you, but I've rechecked and it should be working.

**Comment by AlexLuya** [comment]
## I followed your suggestions("deleting lines from 121 to the end the current Cabal file "),got these:

:~/scion-class-browser$ cabal install
Resolving dependencies...
Configuring terminfo-0.3.2.3...
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ncurses.h usability... no
checking ncurses.h presence... no
checking for ncurses.h... no
checking curses.h usability... no
checking curses.h presence... no
checking for curses.h... no
configure: error: curses headers could not be found, so this package cannot be built
See `config.log' for more details.(***********************************I can't find`config.log',where is it?***************************)
cabal: Error: some packages failed to install:
haskeline-0.6.4.5 depends on terminfo-0.3.2.3 which failed to install.
scion-browser-0.1.3.4 depends on terminfo-0.3.2.3 which failed to install.
terminfo-0.3.2.3 failed during the configure step. The exception was:
ExitFailure 1

**Comment by serras** [comment]
That means that you have problems installing terminfo. Try to install packages `libncurses5-dev` and `libncursesw5-dev`, them try to install `terminfo` alone by running `cabal install terminfo`. If it builds correctly, then continue installing `scion-browser`.

**Comment by AlexLuya** [comment]
Followed your suggestion,it works now,thx.There is another problem.With every eclipse startup,it will ask to build local database,if YES, it will take long time to  "building local database",and consume about 2GB RAM.

**Comment by serras** [comment]
This is a known limitation of scion-browser: building a database of the entire Hackage takes loads of RAM. You can wait to the next scion-browser version, where this problem is solved.

**Comment by AlexLuya** [comment]
Ok,thank you.
