### ISSUE TITLE
Fails to build on GHC, version 7.0.4

### ISSUE THREAD

**Issue by avaranovich** [serras/scion-class-browser#17]
Building scion-browser-0.2.4...

src/Scion/PersistentBrowser/Query.hs:7:8:
    Could not find module `Database.Persist.Base':
      Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
scion-browser-0.2.4 failed during the building phase. The exception was:
ExitFailure 1

**Comment by serras** [comment]
Which version of Persistent are you using? There was a new release some
days ago, maybe it's breaking something.

You may try running `cabal install persistent-0.6.*` in your terminal and
then try scion-browser again.
El 27/01/2012 12:55, "Andrei Varanovich" <
reply@reply.github.com>
escribi:

**Comment by avaranovich** [comment]
persistent-0.7.0.1

**Comment by serras** [comment]
By now, you can try to use `cabal install persistent-0.6.* scion-browser`
to install everything. It should work.
El 27/01/2012 15:02, "Andrei Varanovich" <
reply@reply.github.com>
escribi:

**Comment by avaranovich** [comment]
dhcp86:scion-class-browser varanovich$ cabal install persistent-0.6.4.4
scion-browser
Building scion-browser-0.2.4...

src/Scion/PersistentBrowser/Query.hs:7:8:
    Could not find module `Database.Persist.Base'
    It is a member of the hidden package`persistent-0.6.4.4'.
    Perhaps you need to add `persistent' to the build-depends in your
.cabal file.

Should I mess with .cabal file?

On Fri, Jan 27, 2012 at 9:23 PM, Alejandro Serrano <
reply@reply.github.com

**Comment by serras** [comment]
I've just uploaded a new version of scion-browser which moves everything to Persistent 0.7. So now it should work flawlessly run by issuing `cabal install scion-browser`. Thanks for the report.
