### ISSUE TITLE
GHC 7.2.2 fails to build (FlexibleInstances)

### ISSUE THREAD

**Issue by codeweaverx** [serras/scion-class-browser#19]
On ghc7.2.2, I several of this kind of error in Json.hs and Query.hs

src/Scion/PersistentBrowser/Instances/Json.hs:90:10:
    Illegal instance declaration for `ToJSON DbTyVar'
      (All instance types must be of the form (T a1 ... an)
       where a1 ... an are *distinct type variables*,
       and each type variable appears at most once in the instance head.
       Use -XFlexibleInstances if you want to disable this.)
    In the instance declaration for`ToJSON DbTyVar'

I was able to build upon adding FlexibleInstances to the relevant files, but this may not be the correct fix.

(discovered as a result of this thread over on sourceforge:  http://sourceforge.net/projects/eclipsefp/forums/forum/371922/topic/4777573/index/page/2  )

**Comment by avaranovich** [comment]
Try to add this

{-# LANGUAGE OverloadedStrings, TypeSynonymInstances, FlexibleInstances #-}

into Json.hs and Query.hs

That would be cool if this is fixed in the repository as well.

**Comment by JPMoresmau** [comment]
I have corrected this in my fork and uploaded 0.2.6, since the scion-browser maintainer wasn't immediately available. Hope it works for you now.

**Comment by codeweaverx** [comment]
Yes, that works fine. Thank you.
