### ISSUE TITLE
Parsing(?) error in 0.2.6

### ISSUE THREAD

**Issue by aivarannamaa** [serras/scion-class-browser#21]
I get error using scion-browser from EclipseFP. I have scion-browser 0.2.6, buildwrapper 0.4.1 and EclipseFP 2.2.2 and I get following output (I'm posting tail of it) from scion-browser. JP Moresmau thought it may indicate a bug in scion-browser (https://sourceforge.net/projects/eclipsefp/forums/forum/371922/topic/4988318):

[...]

Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK 

Date: Fri, 03 Feb 2012 12:33:29 GMT

Server: Apache/2.2.9 (Debian) mod_python/3.3.1 Python/2.5.2

Last-Modified: Sun, 27 Nov 2011 21:01:50 GMT

ETag: "1f8a510-40cf-4b2bdb1e54b80"

Accept-Ranges: bytes

Content-Length: 16591

Vary: Accept-Encoding

Content-Type: text/plain

Download http://hackage.haskell.org/packages/archive/aeson/0.6.0.0/doc/html/aeson.txt
Sending:
GET /packages/archive/aeson/0.6.0.0/doc/html/aeson.txt HTTP/1.1

Host: hackage.haskell.org

Content-Length: 0

User-Agent: hs-HTTP-4000.0.9

Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK 

Date: Fri, 03 Feb 2012 12:33:30 GMT

Server: Apache/2.2.9 (Debian) mod_python/3.3.1 Python/2.5.2

Last-Modified: Fri, 03 Feb 2012 02:35:28 GMT

ETag: "1fd6923-78e0-4b8062a6ddc00"

Accept-Ranges: bytes

Content-Length: 30944

Vary: Accept-Encoding

Content-Type: text/plain

scion-browser.exe: TyParen NoDoc (TyVar NoDoc (Ident NoDoc "m"))

**Comment by kamilc** [comment]
I also got the same error:

Download http://hackage.haskell.org/packages/archive/pandoc/1.8.2.1/doc/html/pandoc.txt
Sending:
GET /packages/archive/pandoc/1.8.2.1/doc/html/pandoc.txt HTTP/1.1
Host: hackage.haskell.org
Content-Length: 0
User-Agent: hs-HTTP-4000.0.9

Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK 
Date: Sat, 04 Feb 2012 14:20:17 GMT
Server: Apache/2.2.9 (Debian) mod_python/3.3.1 Python/2.5.2
Last-Modified: Sat, 06 Aug 2011 19:24:35 GMT
ETag: "1f663e5-9f02-4a9db2a08e2c0"
Accept-Ranges: bytes
Content-Length: 40706
Vary: Accept-Encoding
Content-Type: text/plain

scion-browser: TyParen NoDoc (TyVar NoDoc (Ident NoDoc "m"))

**Comment by serras** [comment]
I've pushed a fix for the problem to the repo. May you try it in your local computer?

**Comment by codeweaverx** [comment]
I had exactly this error too, on OSX 10.7.2 using ghc-7.2.2.  As of the time of this posting, my scion-browser now works on a failed input command for EclipseFP.  Hopefully this is everyone else's experience too.

**Comment by serras** [comment]
Did you try the latest code changes and they work?

**Comment by codeweaverx** [comment]
They appear to.  An input string that caused scion-browser to fail (one that caused the zlib bug mentioned here, that EclipseFP issued) now succeeds.

**Comment by serras** [comment]
Then I close the bug.

**Comment by akaspin** [comment]
Bug still here. GHC 7.0.4, scion-browser 0.2.6

```
Download http://hackage.haskell.org/packages/archive/array/0.3.0.2/doc/html/array.txt
Sending:
GET /packages/archive/array/0.3.0.2/doc/html/array.txt HTTP/1.1

Host: hackage.haskell.org

Content-Length: 0

User-Agent: hs-HTTP-4000.0.9




Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK 

Date: Wed, 29 Feb 2012 05:54:49 GMT

Server: Apache/2.2.9 (Debian) mod_python/3.3.1 Python/2.5.2

Last-Modified: Thu, 18 Nov 2010 12:23:57 GMT

ETag: "1eba71c-5ac7-49552dd26b140"

Accept-Ranges: bytes

Content-Length: 23239

Vary: Accept-Encoding

Content-Type: text/plain




scion-browser.exe: TyParen NoDoc (TyVar NoDoc (Ident NoDoc "a"))
```

**Comment by serras** [comment]
Did you try running the version from the repo? It's not uploaded yer to
Hackage, but it should be fixed there.

**Comment by akaspin** [comment]
Please, expose fix on hackage

**Comment by JPMoresmau** [comment]
There is no API change in that version, so I think 0.2.7 could be released even if a new EclipseFP released is not done at the same time.

**Comment by serras** [comment]
Done! Version 0.2.7 of scion-browser is now in the wild.

**Comment by akaspin** [comment]
Thanks a lot
