### ISSUE TITLE
Install fails - due to Database.Perists

### ISSUE THREAD

**Issue by mnykanen** [serras/scion-class-browser#29]
Trying to compile scion-browser from Hackage fails:

mnykanen@kuo-232109$ cabal install scion-browser
Resolving dependencies...
Configuring scion-browser-0.2.14...
Building scion-browser-0.2.14...
Preprocessing executable 'scion-browser' for scion-browser-0.2.14...

src/Scion/PersistentBrowser/Query.hs:10:8:
    Could not find module `Database.Persist.GenericSql.Raw'
    Use -v to see a list of the files searched for.
ghc --make: /usr/hs/ghc/7.4.1/bin/ghc failure (return code=1)
Failed to install scion-browser-0.2.14
cabal: Error: some packages failed to install:
scion-browser-0.2.14 failed during the building phase. The exception was:
ExitFailure 1

Possible cause: The latest Database.Persist version 1.2. has a new module structure. This old structure was still in 1.5.

**Comment by serras** [comment]
The bug is resolved in the main branch at https://github.com/JPMoresmau/scion-class-browser
