### ISSUE TITLE
Not in scope: data constructor `Atto.Fail'

### ISSUE THREAD

**Issue by ghost** [serras/scion-class-browser#9]
I tried to install the 0.1.3.1 version with ghc 7.0.2 and when i build the cabal package it shows:

cabal build
Preprocessing library scion-browser-0.1.3.1...
Preprocessing executables for scion-browser-0.1.3.1...
Building scion-browser-0.1.3.1...
Registering scion-browser-0.1.3.1...
[22 of 22] Compiling Main             ( src/Main.hs, dist/build/scion-browser/scion-browser-tmp/Main.o )

src/Main.hs:22:17: Not in scope: data constructor `Atto.Fail'

src/Main.hs:23:17: Not in scope: data constructor `Atto.Done'

**Comment by ghost** [comment]
it also happens with ghc 7.0.4

**Comment by serras** [comment]
This was a problem with the new version of attoparsec (0.10). I've fixed it and uploaded a new package to Hackage, so now installing version 0.1.3.3 of scion-browser should solve all the problems.

Thanks for submiting the bug report :)

**Comment by ghost** [comment]
Thank you. It works also with the 0.1.3.4 version
